const splashScreenRoute = 'splas-route';
const loginRoute = 'login-route';
const registerRoute = 'register-route';
const accountRoute = 'account-route';
const forgetPasswordRoute = 'fwd-route';
const mainPageRoute = 'mainpage';
const homePageRoute = 'home-page';
const detailPage = 'detail-page'; 
const webViewRoute = 'web-view' ; 
